version: '2'
services:
  tc-informix:
    image: "appiriodevops/tc-database-scripts:9a09c5ab3538b9f37b81beeea11a574ea4a464d1"
    hostname: informix.cloud.topcoder.com
    container_name: iif_innovator_c
    environment: 
      LICENSE: accept
    ports:
      - "2021:2021"
      - "2022:2022"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    tty: true
